language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "k1ng5l3ym-github"
    token:
      secure: $SONAR_TOKEN
      
jdk:
  - oraclejdk8
  
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
deploy:
  provider: releases
  api_key:
    secure:
  file: target/*.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    
branches:
  except:
    - /^*-v[0-9]/